// <auto-generated />
using System;
using CascadeCache;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CascadeCache.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241113071137_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CascadeCache.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            DateOfBirth = new DateTime(1998, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FirstName = "G",
                            LastName = "Shankar",
                            Position = "Junior developer",
                            Salary = 100m
                        },
                        new
                        {
                            Id = 1002,
                            DateOfBirth = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FirstName = "G",
                            LastName = "Vishal",
                            Position = "Junior developer",
                            Salary = 100m
                        },
                        new
                        {
                            Id = 1003,
                            DateOfBirth = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            FirstName = "G",
                            LastName = "Sreyanth",
                            Position = "Junior developer",
                            Salary = 100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
