version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq_container"
    ports:
      - "5672:5672"  # Main RabbitMQ service
      - "15672:15672"  # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  sender:
    build: ./Sender
    container_name: "sender_app"
    depends_on:
      - rabbitmq  # Ensure RabbitMQ starts first
    environment:
      - RABBITMQ_HOST=rabbitmq  # Ensure correct hostname inside Docker

  receiver:
    build: ./Receiver
    container_name: "receiver_app"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
